spring:
  datasource:
    # DataSource
    url: jdbc:mysql://localhost:8889/java?serverTimezone=Asia/Taipei
    username: root
    password: root
  jpa:
    # SessionFactory
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  messages:
    # i18n
    basename: error.Messages
    encoding: UTF-8
    fallback-to-system-locale: false


##這兩個都移去JavaMVCConfig了
#  mvc:
#    view:
#      # ViewResolver
#      prefix: /WEB-INF/views
#      suffix: .jsp

#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案是成功的
#    suffix: .html
#    encoding: UTF-8
#    mode: HTML5
#    spring:
#      resources:
#        static-locations: classpath:/static/



# tomcat server
server:
  port: 8081
  servlet:
    context-path: /boot    

#custom
password:
  length: 12
